### ISSUE TITLE
geotiff download - product=NDVI

### ISSUE THREAD

**Issue by nkjack** [terravion/terravion-examples#27]
Hey,

I used the main.py from geotiff download and got my links to download the necessary tiff files. 
I selected the NDVI product when used the main.py script and now I got the tiff files successfully. 

The issue is that I am not sure what are the 4 channels of my NDVI tiff files. I did not find any helpful documentation from the TerrAvion api about it. Is there any way you could guide me with it?

Thanks a lot,
Best,
Noam.

**Comment by wmaiouiru** [comment]
@wmaiouiru TODO update https://api2.terravion.com doc
