### ISSUE TITLE
Update OpenLayers Example

### ISSUE THREAD

**Issue by Andrauss** [terravion/terravion-examples#29]
I'm using the V1 API (https://api.terravion.com/v1/users/{user_id}/layers/tiles/{z}/{x}/{y}.png) to display layers in OpenLayers it's working fine. 
In V2 API (https://api2.terravion.com/users/{user_id}/{z}/{x}/{y}.png) the same example not working anymore (returning empty .png), if possible update your example for newer API version .

Check the example at my Github https://github.com/Andrauss/terravion-open-layers-example/blob/master/TerraVionTest.html

**Comment by wmaiouiru** [comment]
Hello @Andrauss Apologies for the confusion. 
I have updated our example and created a pull request in your repo.
https://github.com/terravion/terravion-examples/commit/4b3e836b67ae4e181f210e900ca435a779d49fe3

**Comment by Andrauss** [comment]
Working fine now. I have other questions about a-b params, but I'll email you.

**Comment by jgtoriginal** [comment]
Hello @Andrauss 
We are glad that it's working for you know.
And just for the records, if you think your questions might help others encountering similar issues, please post them here by opening a new issue.
Thanks again.
